#!/usr/bin/env python3
"""
nb_to_report.py — Jupyter notebook → LaTeX fragment extractor.

Provides :class:`NotebookExtractor`, which reads a ``.ipynb`` file and writes:

  1. ``auto_nb_figures.tex``  — ``\\begin{figure}`` blocks for the Results section.
  2. ``auto_nb_code.tex``     — ``\\begin{Code}`` blocks for the Analysis Code section.
  3. ``pycode/nb_cells/``     — one ``.py`` snippet per code cell + a runnable bundle.

The class reuses :class:`~extract.SourceExtractor`'s shared LaTeX helpers
(:func:`~extract.tex_escape`, :func:`~extract.code_float`,
:func:`~extract.figure_float`) so that the two modules stay in sync.

Usage
-----
From the command line (run from your lab directory)::

    python3 pycode/nb_to_report.py                              # uses NB_PATH constant
    python3 pycode/nb_to_report.py pycode/my_notebook.ipynb     # explicit path

Snakemake passes the notebook path as the first positional argument
(see the ``extract_notebook`` rule in the Snakefile).

After running, enable the outputs in ``report.tex``::

    \\input{auto_nb_figures}
    \\input{auto_nb_code}

Configure the constants below (especially ``FIGURE_META``) per lab.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

# Import shared LaTeX helpers from extract.py (sibling module).
# nb_to_report.py is always run/imported from the repo root, with pycode/ on
# sys.path (guaranteed by Snakemake and by the __main__ block below).
from extract import SourceExtractor, code_float, figure_float, tex_escape

# ---------------------------------------------------------------------------
# Lab-specific configuration — edit these for each new lab
# ---------------------------------------------------------------------------

NB_PATH: Path = Path("analysis.ipynb")   # fallback notebook path
FIG_TEX: Path = Path("pycode/nb_snippets/auto_nb_figures.tex")
CODE_TEX: Path = Path("pycode/nb_snippets/auto_nb_code.tex")
NB_CELLS_DIR: Path = Path("pycode/nb_snippets")
PLOTS_DIR: Path = Path("plots")

# Map plot filename → (latex_label, caption_text).
# The label must match any existing \\label{} in report.tex.
FIGURE_META: dict[str, tuple[str, str]] = {
    "nb_cavity_decay.png": ("fig:nb-cavity-decay", r"QuTiP simulation of a Fock $|3\rangle$ state decaying in a lossy cavity ($\kappa=1$)."),
}

# Width overrides for wide/narrow figures (default is \\linewidth).
WIDTH: dict[str, str] = {}

# ---------------------------------------------------------------------------


class NotebookExtractor:
    """
    Converts a Jupyter notebook to LaTeX fragments for inclusion in report.tex.

    Composes a :class:`~extract.SourceExtractor` instance so that shared
    LaTeX-emission helpers stay DRY across both modules.

    Parameters
    ----------
    nb_path:
        Path to the ``.ipynb`` file to extract from.
    figure_meta:
        Mapping of ``plot_filename → (label, caption)`` for figure floats.
    width:
        Optional per-file width overrides for ``\\includegraphics``.
    fig_tex:
        Output path for the figures ``.tex`` fragment.
    code_tex:
        Output path for the code-cells ``.tex`` fragment.
    nb_cells_dir:
        Directory where per-cell ``.py`` snippets are written.
    plots_dir:
        Directory where plot files live (used for existence checks).
    """

    def __init__(
        self,
        nb_path: Path = NB_PATH,
        *,
        figure_meta: dict[str, tuple[str, str]] | None = None,
        width: dict[str, str] | None = None,
        fig_tex: Path = FIG_TEX,
        code_tex: Path = CODE_TEX,
        nb_cells_dir: Path = NB_CELLS_DIR,
        plots_dir: Path = PLOTS_DIR,
        wrap_code: bool = True,
        max_width: int = 60,
    ) -> None:
        self.nb_path = nb_path
        self.figure_meta: dict[str, tuple[str, str]] = figure_meta or FIGURE_META
        self.width: dict[str, str] = width or WIDTH
        self.fig_tex = fig_tex
        self.code_tex = code_tex
        self.nb_cells_dir = nb_cells_dir
        self.plots_dir = plots_dir
        self.wrap_code = wrap_code
        self.max_width = max_width
        self._extractor = SourceExtractor()   # shared LaTeX helpers

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    def run(self) -> None:
        """Parse the notebook and write all output files."""
        self.nb_cells_dir.mkdir(parents=True, exist_ok=True)

        nb = json.loads(self.nb_path.read_text(encoding="utf-8"))
        cells = nb["cells"]

        py_lines = self._py_bundle_header()
        fig_lines: list[str] = [
            "% auto_nb_figures.tex — generated by nb_to_report.py",
            r"% Place \input{auto_nb_figures} inside Results section.",
            "",
        ]
        code_lines: list[str] = [
            "% auto_nb_code.tex — generated by nb_to_report.py",
            r"% Place \input{auto_nb_code} inside Analysis Code section.",
            "",
        ]

        current_heading = ""
        for cell in cells:
            ctype = cell["cell_type"]
            src = (
                cell["source"]
                if isinstance(cell["source"], list)
                else cell["source"].splitlines(keepends=True)
            )

            if ctype == "markdown":
                current_heading = self._heading_from_markdown(src)
                continue
            if ctype != "code":
                continue
            code = "".join(src).strip()
            if not code:
                continue

            if self.wrap_code:
                code = self._wrap_code(code, max_width=self.max_width)

            # Append to runnable Python bundle
            sep = "─" * 56
            py_lines += [f"\n# {sep}\n# {current_heading}\n# {sep}", code, ""]

            # Figure floats for any plot files saved in this cell
            for plot_file in self._find_plots(src):
                if plot_file not in self.figure_meta:
                    continue
                label, caption = self.figure_meta[plot_file]
                w = self.width.get(plot_file, r"\linewidth")
                fig_lines += figure_float(plot_file, label, caption, width=w)

            # Code float for this cell
            snippet_name = re.sub(r"[^a-z0-9]+", "_", current_heading.lower()).strip("_")
            snippet_path = self.nb_cells_dir / f"_nb_{snippet_name}.py"
            snippet_path.write_text(
                f"# Notebook cell — {current_heading}\n{code}\n",
                encoding="utf-8",
            )
            snippet_rel = f"{self.nb_cells_dir}/_nb_{snippet_name}.py"
            code_lines += code_float(snippet_rel, current_heading)

        # Write outputs
        (self.nb_cells_dir / "nb_cells.py").write_text(
            "\n".join(py_lines), encoding="utf-8"
        )
        self.fig_tex.write_text("\n".join(fig_lines), encoding="utf-8")
        self.code_tex.write_text("\n".join(code_lines), encoding="utf-8")

        print(f"Written: {self.nb_cells_dir}/nb_cells.py")
        print(f"Written: {self.fig_tex}  ({len([l for l in fig_lines if '\\begin{figure}' in l])} figures)")
        print(f"Written: {self.code_tex}  ({len([l for l in code_lines if '\\begin{Code}' in l])} cells)")
        print(f"Snippets in: {self.nb_cells_dir}/")

    # ------------------------------------------------------------------
    # Line wrapping logic
    # ------------------------------------------------------------------

    def _wrap_code(self, code: str, max_width: int = 75) -> str:
        """
        Wrap long Python lines (primarily at dots in method chains).
        """
        lines = code.splitlines()
        wrapped = []
        for line in lines:
            if len(line) <= max_width:
                wrapped.append(line)
                continue

            # Heuristic wrapping at dots
            cur = line
            cumulative_open = 0
            while len(cur) > max_width:
                best_match = None
                for m in re.finditer(r"[^\s]\.", cur):
                    if m.start() < max_width - 2:
                        best_match = m
                    else:
                        break
                
                if not best_match:
                    break
                    
                split_idx = best_match.start() + 1
                prefix = cur[:split_idx]
                suffix = cur[split_idx:]
                
                # Update cumulative open count from the prefix
                cumulative_open += prefix.count('(') - prefix.count(')')
                
                # Check parens to see if we need a backslash
                if cumulative_open <= 0:
                    prefix += "\\"
                
                wrapped.append(prefix)
                indent = re.match(r"^(\s*)", line).group(1)
                cur = indent + "    " + suffix
                
            wrapped.append(cur)
            
        return "\n".join(wrapped)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _py_bundle_header(self) -> list[str]:
        return [
            "#!/usr/bin/env python3",
            f'"""Auto-generated from {self.nb_path.name} by nb_to_report.py."""',
            "",
            "# fmt: off",
            "import sys, os",
            "from pathlib import Path",
            "ROOT = Path('.').resolve()",
            "os.chdir(ROOT)",
            "sys.path.insert(0, str(ROOT / 'pycode'))",
            "",
            "# ---------------------------------------------------------------------------",
        ]

    @staticmethod
    def _heading_from_markdown(src: list[str]) -> str:
        """Extract a human-readable heading from a markdown cell."""
        for line in src:
            m = re.match(r"^#{1,4}\s+(.*)", line.strip())
            if m:
                return m.group(1).strip()
        for line in src:
            text = line.strip().lstrip("#").strip()
            if text:
                return text
        return "Notebook cell"

    def _find_plots(self, code_lines: list[str]) -> list[str]:
        """Return plot filenames referenced in *code_lines* that exist on disk."""
        found = []
        for line in code_lines:
            m = re.search(r"PLOTS_DIR\s*/\s*['\"]([^'\"]+\.png)['\"]", line)
            if m and (self.plots_dir / m.group(1)).exists():
                found.append(m.group(1))
        return found


# ---------------------------------------------------------------------------
# Module-level shim (backward-compat: ``extract(nb_path)`` still works)
# ---------------------------------------------------------------------------

def extract(nb_path: Path = NB_PATH) -> None:
    """Backward-compatible shim — delegates to :class:`NotebookExtractor`."""
    NotebookExtractor(nb_path).run()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    _nb = Path(sys.argv[1]) if len(sys.argv) > 1 else NB_PATH
    if not _nb.exists():
        print(f"Error: notebook not found: {_nb}", file=sys.stderr)
        sys.exit(1)
    # Ensure pycode/ is importable (when run as python3 pycode/nb_to_report.py)
    _pycode = Path(__file__).parent
    if str(_pycode) not in sys.path:
        sys.path.insert(0, str(_pycode))
    NotebookExtractor(_nb).run()
