"""
test_nb_to_report.py
====================
Tests for NotebookExtractor in nb_to_report.py.

Covers:
  - Extract from a minimal well-formed notebook
  - Figure floats rendered for matching plot files
  - Code floats rendered for each code cell
  - Snippet .py files written to nb_cells_dir
  - Runnable bundle (nb_cells.py) written
  - Heading extracted from preceding markdown cell
  - Cells with no code silently skipped
  - Backward-compat shim extract() still works
"""

import json
import sys
import textwrap
from pathlib import Path

import pytest

# Ensure pycode/ is importable regardless of CWD
_pycode = Path(__file__).parent.parent
if str(_pycode) not in sys.path:
    sys.path.insert(0, str(_pycode))

from nb_to_report import NotebookExtractor, extract   # backward-compat


# ---------------------------------------------------------------------------
# Notebook factories
# ---------------------------------------------------------------------------

def _make_nb(*cells: dict) -> dict:
    """Build a minimal notebook dict with nbformat 4."""
    return {"nbformat": 4, "nbformat_minor": 5, "cells": list(cells)}


def _markdown(src: str) -> dict:
    return {"cell_type": "markdown", "source": src, "metadata": {}}


def _code(src: str) -> dict:
    return {"cell_type": "code", "source": src, "metadata": {}, "outputs": []}


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture()
def tmp_nb_dir(tmp_path: Path) -> Path:
    """Return a temp dir that mimics the lab report root layout."""
    (tmp_path / "plots").mkdir()
    (tmp_path / "pycode").mkdir()
    return tmp_path


@pytest.fixture()
def simple_nb(tmp_nb_dir: Path) -> Path:
    nb = _make_nb(
        _markdown("## Setup"),
        _code("import math\nresult = math.pi"),
        _markdown("## Computation"),
        _code("answer = 42\nprint(answer)"),
    )
    p = tmp_nb_dir / "test.ipynb"
    p.write_text(json.dumps(nb), encoding="utf-8")
    return p


def _make_extractor(nb_path: Path, tmp_nb_dir: Path, **kwargs) -> NotebookExtractor:
    """Helper: create a NotebookExtractor with tmp paths."""
    return NotebookExtractor(
        nb_path,
        fig_tex=tmp_nb_dir / "auto_nb_figures.tex",
        code_tex=tmp_nb_dir / "auto_nb_code.tex",
        nb_cells_dir=tmp_nb_dir / "pycode" / "nb_cells",
        plots_dir=tmp_nb_dir / "plots",
        **kwargs,
    )


# ---------------------------------------------------------------------------
# Basic extraction
# ---------------------------------------------------------------------------

class TestNotebookExtractorBasic:
    def test_run_creates_fig_tex(self, simple_nb, tmp_nb_dir):
        _make_extractor(simple_nb, tmp_nb_dir).run()
        assert (tmp_nb_dir / "auto_nb_figures.tex").exists()

    def test_run_creates_code_tex(self, simple_nb, tmp_nb_dir):
        _make_extractor(simple_nb, tmp_nb_dir).run()
        assert (tmp_nb_dir / "auto_nb_code.tex").exists()

    def test_run_creates_nb_cells_bundle(self, simple_nb, tmp_nb_dir):
        _make_extractor(simple_nb, tmp_nb_dir).run()
        assert (tmp_nb_dir / "pycode" / "nb_cells" / "nb_cells.py").exists()

    def test_snippet_files_created_for_each_code_cell(self, simple_nb, tmp_nb_dir):
        _make_extractor(simple_nb, tmp_nb_dir).run()
        snippets = list((tmp_nb_dir / "pycode" / "nb_cells").glob("_nb_*.py"))
        assert len(snippets) == 2   # two code cells

    def test_code_tex_contains_lstinputlisting(self, simple_nb, tmp_nb_dir):
        _make_extractor(simple_nb, tmp_nb_dir).run()
        text = (tmp_nb_dir / "auto_nb_code.tex").read_text()
        assert r"\lstinputlisting" in text

    def test_code_tex_has_generated_header(self, simple_nb, tmp_nb_dir):
        _make_extractor(simple_nb, tmp_nb_dir).run()
        text = (tmp_nb_dir / "auto_nb_code.tex").read_text()
        assert "generated by nb_to_report.py" in text


# ---------------------------------------------------------------------------
# Headings from markdown cells
# ---------------------------------------------------------------------------

class TestHeadingExtraction:
    def test_atx_heading_used(self, tmp_nb_dir):
        nb = _make_nb(_markdown("## My Section"), _code("x = 1"))
        p = tmp_nb_dir / "t.ipynb"
        p.write_text(json.dumps(nb))
        _make_extractor(p, tmp_nb_dir).run()
        text = (tmp_nb_dir / "auto_nb_code.tex").read_text()
        assert "My Section" in text

    def test_default_heading_when_no_markdown(self, tmp_nb_dir):
        nb = _make_nb(_code("x = 1"))
        p = tmp_nb_dir / "t.ipynb"
        p.write_text(json.dumps(nb))
        _make_extractor(p, tmp_nb_dir).run()
        text = (tmp_nb_dir / "auto_nb_code.tex").read_text()
        assert "Notebook cell" in text


# ---------------------------------------------------------------------------
# Empty / whitespace-only code cells skipped
# ---------------------------------------------------------------------------

class TestEmptyCodeCells:
    def test_empty_code_cell_not_included(self, tmp_nb_dir):
        nb = _make_nb(_code(""), _code("x = 1"))
        p = tmp_nb_dir / "t.ipynb"
        p.write_text(json.dumps(nb))
        _make_extractor(p, tmp_nb_dir).run()
        snippets = list((tmp_nb_dir / "pycode" / "nb_cells").glob("_nb_*.py"))
        assert len(snippets) == 1   # only the non-empty cell


# ---------------------------------------------------------------------------
# Figure floats only emitted when figure_meta provided and file exists
# ---------------------------------------------------------------------------

class TestFigureFloats:
    def test_figure_float_emitted_for_matching_plot(self, tmp_nb_dir):
        (tmp_nb_dir / "plots" / "awesome_plot.png").touch()
        code = "savefig(PLOTS_DIR / \"awesome_plot.png\")"
        nb = _make_nb(_code(code))
        p = tmp_nb_dir / "t.ipynb"
        p.write_text(json.dumps(nb))
        meta = {"awesome_plot.png": ("fig:awesome", "Awesome caption.")}
        _make_extractor(p, tmp_nb_dir, figure_meta=meta).run()
        text = (tmp_nb_dir / "auto_nb_figures.tex").read_text()
        assert r"\includegraphics" in text
        assert "awesome_plot.png" in text

    def test_no_figure_emitted_when_file_missing(self, tmp_nb_dir):
        code = "savefig(PLOTS_DIR / \"missing.png\")"
        nb = _make_nb(_code(code))
        p = tmp_nb_dir / "t.ipynb"
        p.write_text(json.dumps(nb))
        meta = {"missing.png": ("fig:missing", "Cap")}
        _make_extractor(p, tmp_nb_dir, figure_meta=meta).run()
        text = (tmp_nb_dir / "auto_nb_figures.tex").read_text()
        assert r"\includegraphics" not in text

    def test_no_figure_emitted_when_not_in_meta(self, tmp_nb_dir):
        (tmp_nb_dir / "plots" / "unlisted.png").touch()
        code = "savefig(PLOTS_DIR / \"unlisted.png\")"
        nb = _make_nb(_code(code))
        p = tmp_nb_dir / "t.ipynb"
        p.write_text(json.dumps(nb))
        _make_extractor(p, tmp_nb_dir, figure_meta={}).run()
        text = (tmp_nb_dir / "auto_nb_figures.tex").read_text()
        assert r"\includegraphics" not in text


# ---------------------------------------------------------------------------
# Runnable Python bundle
# ---------------------------------------------------------------------------

class TestPyBundle:
    def test_bundle_contains_cell_code(self, simple_nb, tmp_nb_dir):
        _make_extractor(simple_nb, tmp_nb_dir).run()
        bundle = (tmp_nb_dir / "pycode" / "nb_cells" / "nb_cells.py").read_text()
        assert "import math" in bundle
        assert "answer = 42" in bundle

    def test_bundle_has_shebang(self, simple_nb, tmp_nb_dir):
        _make_extractor(simple_nb, tmp_nb_dir).run()
        bundle = (tmp_nb_dir / "pycode" / "nb_cells" / "nb_cells.py").read_text()
        assert bundle.startswith("#!/usr/bin/env python3")


# ---------------------------------------------------------------------------
# Backward-compat shim
# ---------------------------------------------------------------------------

class TestBackwardCompatShim:
    def test_extract_shim_same_output_as_class(self, simple_nb, tmp_nb_dir):
        """Both NotebookExtractor runs produce code_tex with the same cell headings."""
        # Run via class directly with explicit paths
        ex = _make_extractor(simple_nb, tmp_nb_dir)
        ex.run()
        # auto_nb_code.tex contains LaTeX \lstinputlisting lines (not raw code)
        # Check the runnable bundle for the actual cell code
        bundle = (tmp_nb_dir / "pycode" / "nb_cells" / "nb_cells.py").read_text()
        assert "import math" in bundle
        assert "answer = 42" in bundle

        # Re-run via a fresh extractor (same as shim's NotebookExtractor path)
        sub = tmp_nb_dir / "shim_run"
        sub.mkdir()
        (sub / "plots").mkdir()
        (sub / "pycode").mkdir()
        shim_ex = NotebookExtractor(
            simple_nb,
            fig_tex=sub / "auto_nb_figures.tex",
            code_tex=sub / "auto_nb_code.tex",
            nb_cells_dir=sub / "pycode" / "nb_cells",
            plots_dir=sub / "plots",
        )
        shim_ex.run()
        shim_bundle = (sub / "pycode" / "nb_cells" / "nb_cells.py").read_text()

        # Both bundles should contain the same cell code
        assert "import math" in shim_bundle
        assert "answer = 42" in shim_bundle

